name: SoundEffect
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.soundeffect.SoundEffect

author: hexosse
website: www.github.hexocraftapi

depend: []
softdepend: []

permissions:
  SoundEffect.admin: {description: All permissions, default: false}
  SoundEffect.*:
    default: op
    children:
        SoundEffect.admin: true
