name: SoundEffect
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.soundeffect.SoundEffectPlugin

author: hexosse
website: www.github.hexocraftapi

depend: []
softdepend: []

permissions:
  SoundEffect.admin: {description: All permissions, default: false}
  SoundEffect.play.sound: {description: Play a sound, default: false}
  SoundEffect.*:
    default: op
    children:
        SoundEffect.admin: true
  SoundEffect.admin:
    children:
        SoundEffect.play.sound: true
